#ifndef PACKER_ERRORS_H__
# define PACKER_ERRORS_H__

#define PACKER_ERROR_OPEN_FILE                      -1
#define PACKER_ERROR_CORRUPTED_EXECUTABLE           -2
#define PACKER_ERROR_UNKNOWN_COMPRESSION_ALGORITHM  -3
#define PACKER_ERROR_COMRPESSING_EXECUTABLE         -4
#define PACKER_ERROR_CREATING_TEXT_SECTION          -5
#define PACKER_ERROR_CREATING_IDATA_SECTION         -6
#define PACKER_ERROR_FIXING_TEXT_SECTION            -7
#define PACKER_ERROR_BUILDING_FINAL_EXECUTABLE      -8

#endif /* errors.h */
